trigger: none
pr: none

variables:
  proxyArtifactName: jss-proxy
  proxyBuildPath: $(System.DefaultWorkingDirectory)/packages/sitecore-jss-proxy
  feedName: weareyou
  nodeVersion: 12.16.1

stages:
- stage: Build
  dependsOn: []
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: NodeTool@0
      displayName: 'Use Node.js $(nodeVersion)'
      inputs:
        versionSpec: $(nodeVersion)

    - task: Npm@1
      displayName: Install Packages
      inputs:
        command: ci

    - task: Npm@1
      displayName: Bootstrapping packages WAY
      inputs:
        command: custom
        customCommand: run bootstrap-packages:weareyou

    - task: Npm@1
      displayName: Build-packages WAY
      inputs:
        command: custom
        customCommand: run build-packages:weareyou

    - task: PublishPipelineArtifact@1
      displayName: Publish Pipeline Artifact Proxy
      inputs:
        path: $(proxyBuildPath)
        artifact: $(proxyArtifactName)

- stage: Publish
  dependsOn: Build
  jobs:
  - job: Publish
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: none
    
    - task: NodeTool@0
      displayName: 'Use Node.js $(nodeVersion)'
      inputs:
        versionSpec: $(nodeVersion)

    - task: DownloadPipelineArtifact@2
      displayName: Download Pipeline Artifact Proxy
      inputs:
        artifact: $(proxyArtifactName)
        path: $(Build.SourcesDirectory)

    - task: Npm@1
      displayName: Publish Package
      enabled: false
      inputs:
        command: publish
        publishRegistry: useFeed
        publishFeed: $(feedName)